### ISSUE TITLE
Connecting ESP32-S2 and USB Modem - Error HUB: Root port reset failed

### ISSUE THREAD

**Issue by lorenzopeluso** [chegewara/esp32-usb-host#2]
Hi Chegewara,

I am trying to use your USB Host CDC-ACM to connect an LTE Modem via USB to my ESP32-S2 using development board.

The USB port Modem-side is powered-on and D+ and D- correctly connected. 

Unfortunately, I have the following error and no other events happen. 

I (261) cpu_start: Starting scheduler on PRO CPU.
I (326) : install status: 0
I (326) : client register status: 0
E (576) HUB: Root port reset failed
E (131536) HUB: Root port reset failed
E (135496) HUB: Root port reset failed
E (139316) HUB: Root port reset failed

Might you help me with some suggestions on how to proceed? 

Do you know what does this error mean? 

Thanks a lot in advanc e for you help.
BR,
Lorenzo.

**Comment by chegewara** [comment]
Please try to change this value to `255` in menuconfig `CONFIG_USB_HOST_CONTROL_TRANSFER_MAX_SIZE`.
May be related:
https://github.com/espressif/esp-idf/issues/7799
