### ISSUE TITLE
fatal error: usb/usb_host.h: No such file or directory

### ISSUE THREAD

**Issue by vigyanabikshu1** [chegewara/esp32-usb-host#5]
I am getting the following error

In file included from /home/v-robotics/esp2/test/esp32-usb-host-main/components/usb_host/include/usb_acm.hpp:2,
                 from /home/v-robotics/esp2/test/esp32-usb-host-main/components/usb_host/acm/usb_acm.cpp:4:
/home/v-robotics/esp2/test/esp32-usb-host-main/components/usb_host/include/usb_device.hpp:3:10: fatal error: usb/usb_host.h: No such file or directory
 #include "usb/usb_host.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.

idf.py --version
ESP-IDF v4.4-beta1-dirty

**Comment by chegewara** [comment]
And what board do you have set with `set-target`?

**Comment by vigyanabikshu1** [comment]
Sorry, My mistake. set-target esp32s2 solved. Now getting the following error

/home/v-robotics/esp4/test/esp32-usb-host/components/usb_host/host/usb_host.cpp: In member function 'bool USBhost::init(bool)':
/home/v-robotics/esp4/test/esp32-usb-host/components/usb_host/host/usb_host.cpp:85:5: error: 'const usb_host_client_config_t' has no non-static data member named 'async'
     };
     ^
/home/v-robotics/esp4/test/esp32-usb-host/components/usb_host/host/usb_host.cpp: In member function 'bool USBhost::open(const usb_host_client_event_msg_t*)':
/home/v-robotics/esp4/test/esp32-usb-host/components/usb_host/host/usb_host.cpp:100:15: warning: unused variable 'err' [-Wunused-variable]
     esp_err_t err = usb_host_device_open(client_hdl, event_msg->new_dev.address, &dev_hdl);
               ^~~
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by chegewara** [comment]
Hi,
its most likely because i am working and testing with master branch and espressif USB host component is still WiP and is changing.

**Comment by vigyanabikshu1** [comment]
I tried again with latest version 4.4 stable release. Now I can compile without any problem. but it is not detecting USB drive now.
Output
I (284) example: usb_host_install...
I (314) example: wait_for_msc_device...
I (314) example: Waiting for USB stick to be connected

Double checked connection
+5V
DM    IO19
DP    IO20
GND

**Comment by vigyanabikshu1** [comment]
Sorry, it was my mistake. The USB type A connector DM and DP pins were short. Now works MSC fine.
